import { v4 as uuidv4 } from 'uuid';
import type { ClothingItem } from './types';

/**
 * Default men's wardrobe – used to pre-populate the closet on first load.
 * All items have isDefault=true and isDirty=false.
 */
const defaultWardrobe: ClothingItem[] = [
  // ─── Tops ────────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'White Crew-Neck T-Shirt',
    category: 'top',
    subcategory: 't-shirt',
    color: 'white',
    colorFamily: 'neutral',
    style: ['casual', 'versatile'],
    formality: 1,
    weatherSuitability: { minTemp: 60, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Black V-Neck T-Shirt',
    category: 'top',
    subcategory: 't-shirt',
    color: 'black',
    colorFamily: 'neutral',
    style: ['casual', 'versatile'],
    formality: 1,
    weatherSuitability: { minTemp: 60, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Navy Blue Polo',
    category: 'top',
    subcategory: 'polo',
    color: 'navy',
    colorFamily: 'cool',
    style: ['smart-casual', 'business-casual', 'golf'],
    formality: 2,
    weatherSuitability: { minTemp: 55, maxTemp: 80, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'White Oxford Shirt',
    category: 'top',
    subcategory: 'button-down',
    color: 'white',
    colorFamily: 'neutral',
    style: ['business-casual', 'smart-casual', 'formal'],
    formality: 4,
    weatherSuitability: { minTemp: 50, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Light Blue Dress Shirt',
    category: 'top',
    subcategory: 'button-down',
    color: 'light-blue',
    colorFamily: 'cool',
    style: ['business-casual', 'formal', 'office'],
    formality: 4,
    weatherSuitability: { minTemp: 50, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Gray Hoodie',
    category: 'top',
    subcategory: 'hoodie',
    color: 'gray',
    colorFamily: 'neutral',
    style: ['casual', 'athletic', 'loungewear'],
    formality: 1,
    weatherSuitability: { minTemp: 40, maxTemp: 65, conditions: ['clear', 'cloudy', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Navy Casual Sweater',
    category: 'top',
    subcategory: 'sweater',
    color: 'navy',
    colorFamily: 'cool',
    style: ['casual', 'smart-casual', 'business-casual'],
    formality: 2,
    weatherSuitability: { minTemp: 40, maxTemp: 65, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Navy Blue Blazer',
    category: 'top',
    subcategory: 'blazer',
    color: 'navy',
    colorFamily: 'cool',
    style: ['business-casual', 'smart-casual', 'formal', 'evening'],
    formality: 4,
    weatherSuitability: { minTemp: 50, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },

  // ─── Bottoms ─────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'Dark Blue Jeans',
    category: 'bottom',
    subcategory: 'jeans',
    color: 'dark-blue',
    colorFamily: 'cool',
    style: ['casual', 'smart-casual', 'versatile'],
    formality: 2,
    weatherSuitability: { minTemp: 45, conditions: ['clear', 'cloudy', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Slim-Fit Khaki Chinos',
    category: 'bottom',
    subcategory: 'chinos',
    color: 'khaki',
    colorFamily: 'warm',
    style: ['business-casual', 'smart-casual', 'versatile'],
    formality: 3,
    weatherSuitability: { minTemp: 50, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Navy Blue Chinos',
    category: 'bottom',
    subcategory: 'chinos',
    color: 'navy',
    colorFamily: 'cool',
    style: ['business-casual', 'smart-casual', 'office'],
    formality: 3,
    weatherSuitability: { minTemp: 50, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Athletic Shorts',
    category: 'bottom',
    subcategory: 'shorts',
    color: 'black',
    colorFamily: 'neutral',
    style: ['athletic', 'gym', 'casual'],
    formality: 1,
    weatherSuitability: { minTemp: 65, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Casual Shorts',
    category: 'bottom',
    subcategory: 'shorts',
    color: 'khaki',
    colorFamily: 'warm',
    style: ['casual', 'weekend'],
    formality: 1,
    weatherSuitability: { minTemp: 70, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Gray Sweatpants',
    category: 'bottom',
    subcategory: 'sweatpants',
    color: 'gray',
    colorFamily: 'neutral',
    style: ['loungewear', 'casual', 'gym'],
    formality: 1,
    weatherSuitability: { minTemp: 40, maxTemp: 65, conditions: ['clear', 'cloudy', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },

  // ─── Shoes ───────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'White Sneakers',
    category: 'shoes',
    subcategory: 'sneakers',
    color: 'white',
    colorFamily: 'neutral',
    style: ['casual', 'smart-casual', 'versatile'],
    formality: 2,
    weatherSuitability: { minTemp: 55, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Running Shoes',
    category: 'shoes',
    subcategory: 'athletic',
    color: 'gray',
    colorFamily: 'neutral',
    style: ['athletic', 'gym', 'run'],
    formality: 1,
    weatherSuitability: { minTemp: 40, conditions: ['clear', 'cloudy', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Brown Casual Shoes',
    category: 'shoes',
    subcategory: 'loafers',
    color: 'brown',
    colorFamily: 'warm',
    style: ['smart-casual', 'business-casual', 'casual'],
    formality: 3,
    weatherSuitability: { minTemp: 45, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Black Leather Dress Shoes',
    category: 'shoes',
    subcategory: 'dress',
    color: 'black',
    colorFamily: 'neutral',
    style: ['formal', 'business-casual', 'office', 'evening'],
    formality: 5,
    weatherSuitability: { minTemp: 45, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Flip-Flops',
    category: 'shoes',
    subcategory: 'sandals',
    color: 'black',
    colorFamily: 'neutral',
    style: ['casual', 'beach', 'summer'],
    formality: 1,
    weatherSuitability: { minTemp: 75, conditions: ['clear'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },

  // ─── Outerwear ───────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'Lightweight Rain Jacket',
    category: 'outerwear',
    subcategory: 'rain-jacket',
    color: 'navy',
    colorFamily: 'cool',
    style: ['casual', 'outdoor', 'athletic'],
    formality: 2,
    weatherSuitability: { conditions: ['rain', 'cloudy', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Denim Jacket',
    category: 'outerwear',
    subcategory: 'jacket',
    color: 'medium-blue',
    colorFamily: 'cool',
    style: ['casual', 'smart-casual'],
    formality: 2,
    weatherSuitability: { minTemp: 50, maxTemp: 70, conditions: ['clear', 'cloudy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Winter Coat',
    category: 'outerwear',
    subcategory: 'coat',
    color: 'charcoal',
    colorFamily: 'neutral',
    style: ['casual', 'smart-casual', 'winter'],
    formality: 3,
    weatherSuitability: { maxTemp: 40, conditions: ['clear', 'cloudy', 'snow', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },

  // ─── Accessories ─────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'Black Leather Belt',
    category: 'accessory',
    subcategory: 'belt',
    color: 'black',
    colorFamily: 'neutral',
    style: ['formal', 'business-casual', 'office'],
    formality: 3,
    weatherSuitability: {},
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Brown Leather Belt',
    category: 'accessory',
    subcategory: 'belt',
    color: 'brown',
    colorFamily: 'warm',
    style: ['casual', 'smart-casual', 'business-casual'],
    formality: 2,
    weatherSuitability: {},
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Analog Watch',
    category: 'accessory',
    subcategory: 'watch',
    color: 'silver',
    colorFamily: 'neutral',
    style: ['casual', 'business-casual', 'formal', 'versatile'],
    formality: 3,
    weatherSuitability: {},
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Baseball Cap',
    category: 'accessory',
    subcategory: 'hat',
    color: 'navy',
    colorFamily: 'cool',
    style: ['casual', 'athletic', 'outdoor'],
    formality: 1,
    weatherSuitability: { conditions: ['clear'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Knit Beanie',
    category: 'accessory',
    subcategory: 'hat',
    color: 'charcoal',
    colorFamily: 'neutral',
    style: ['casual', 'winter', 'outdoor'],
    formality: 1,
    weatherSuitability: { maxTemp: 45, conditions: ['clear', 'cloudy', 'snow', 'windy'] },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },

  // ─── Socks ───────────────────────────────────────────────────────────────
  {
    id: uuidv4(),
    name: 'No-Show Socks',
    category: 'socks',
    subcategory: 'no-show',
    color: 'white',
    colorFamily: 'neutral',
    style: ['casual', 'versatile'],
    formality: 1,
    weatherSuitability: { minTemp: 60 },
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Athletic Socks',
    category: 'socks',
    subcategory: 'crew',
    color: 'white',
    colorFamily: 'neutral',
    style: ['athletic', 'gym', 'casual'],
    formality: 1,
    weatherSuitability: {},
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Dress Socks',
    category: 'socks',
    subcategory: 'dress',
    color: 'black',
    colorFamily: 'neutral',
    style: ['formal', 'business-casual', 'office'],
    formality: 4,
    weatherSuitability: {},
    isDefault: true,
    isDirty: false,
    createdAt: new Date().toISOString(),
  },
];

export default defaultWardrobe;
